# Generated by Django 3.2.16 on 2022-10-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
